#!/bin/sh
#
# Gradle start up script for POSIX generated by the Gradle 'init' task.
#

# Attempt to set APP_HOME
APP_HOME="${APP_HOME:-$(dirname "$0")}"
APP_HOME="$(cd "$APP_HOME" && pwd)"
APP_BASE_NAME=$(basename "$0")

CLASSPATH="$APP_HOME/gradle/wrapper/gradle-wrapper.jar"

# Determine JVM command
JAVACMD="${JAVA_HOME:+"$JAVA_HOME/bin/java"}"
JAVACMD="${JAVACMD:-java}"

exec "$JAVACMD" \
  -classpath "$CLASSPATH" \
  org.gradle.wrapper.GradleWrapperMain \
  "$@"
